on:
  workflow_call:

jobs:
  build-apworld:
    name: APWorld
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure
        run: cmake -B build -DRRAP_BUILD_APWORLD=ON -DRRAP_BUILD_GAME=OFF

      - name: Build
        run: cmake --build build --target rrap_apworld

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: APWorld
          path: build/bin/ringracers.apworld

      - name: List
        if: always()
        run: |
          git status
          cd build
          pwd
          ls -R .
