name: CI

on:
  push:
  pull_request:

jobs:
  build-game:
    name: Client (executables)

    strategy:
      fail-fast: false
      matrix:
        config:
          - label: Windows
            os: windows-latest
            shell: "msys2 {0}"
            cmake_preset: ninja-x86_mingw_static_vcpkg-release
            upload: true

          - label: Ubuntu
            os: ubuntu-latest
            shell: bash
            cmake_preset: ninja-vcpkg-release
            upload: false

    uses: ./.github/workflows/game.yml
    with:
      label: ${{ matrix.config.label }}
      os: ${{ matrix.config.os }}
      shell: ${{ matrix.config.shell }}
      cmake_preset: ${{ matrix.config.cmake_preset }}
      upload: ${{ matrix.config.upload }}
      with_tag: ${{ github.ref_type == 'tag' }}

  build-flatpak:
    name: Client (Flatpak)
    strategy:
      fail-fast: false
    uses: ./.github/workflows/flatpak.yml

  build-apworld:
    name: APWorld
    strategy:
      fail-fast: false
    uses: ./.github/workflows/apworld.yml

  release:
    name: Release
    needs:
      - build-game
      - build-flatpak
      - build-apworld
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/release.yml
    with:
      tag: ${{ github.ref_name }}
